version: "3.8"

services:
  opa:
    image: "openpolicyagent/opa:latest"
    ports:
      - "8181:8181"
    command: run --server --log-level debug --addr=0.0.0.0:8181
  postgres:
    image: "postgres:14.17"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: opademo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
